# Generated by Django 2.2.5 on 2020-04-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200401_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Accuracy',
            new_name='accuracy',
        ),
    ]
